// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.TheLastOne
{

using global::System;
using global::FlatBuffers;

public struct Client_Status : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Client_Status GetRootAsClient_Status(ByteBuffer _bb) { return GetRootAsClient_Status(_bb, new Client_Status()); }
  public static Client_Status GetRootAsClient_Status(ByteBuffer _bb, Client_Status obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Client_Status __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Status { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MapType { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Client_Status> CreateClient_Status(FlatBufferBuilder builder,
      int status = 0,
      int mapType = 0) {
    builder.StartObject(2);
    Client_Status.AddMapType(builder, mapType);
    Client_Status.AddStatus(builder, status);
    return Client_Status.EndClient_Status(builder);
  }

  public static void StartClient_Status(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddStatus(FlatBufferBuilder builder, int status) { builder.AddInt(0, status, 0); }
  public static void AddMapType(FlatBufferBuilder builder, int mapType) { builder.AddInt(1, mapType, 0); }
  public static Offset<Client_Status> EndClient_Status(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Client_Status>(o);
  }
};


}
