// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.TheLastOne
{

using global::System;
using global::FlatBuffers;

public struct Gameitem : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Gameitem GetRootAsGameitem(ByteBuffer _bb) { return GetRootAsGameitem(_bb, new Gameitem()); }
  public static Gameitem GetRootAsGameitem(ByteBuffer _bb, Gameitem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Gameitem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public float X { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool Eat { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Gameitem> CreateGameitem(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      float x = 0.0f,
      float z = 0.0f,
      bool eat = false) {
    builder.StartObject(5);
    Gameitem.AddZ(builder, z);
    Gameitem.AddX(builder, x);
    Gameitem.AddName(builder, nameOffset);
    Gameitem.AddId(builder, id);
    Gameitem.AddEat(builder, eat);
    return Gameitem.EndGameitem(builder);
  }

  public static void StartGameitem(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(2, x, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(3, z, 0.0f); }
  public static void AddEat(FlatBufferBuilder builder, bool eat) { builder.AddBool(4, eat, false); }
  public static Offset<Gameitem> EndGameitem(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Gameitem>(o);
  }
};


}
