// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.TheLastOne
{

using global::System;
using global::FlatBuffers;

public struct Client_id : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Client_id GetRootAsClient_id(ByteBuffer _bb) { return GetRootAsClient_id(_bb, new Client_id()); }
  public static Client_id GetRootAsClient_id(ByteBuffer _bb, Client_id obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Client_id __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Client_id> CreateClient_id(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartObject(1);
    Client_id.AddId(builder, id);
    return Client_id.EndClient_id(builder);
  }

  public static void StartClient_id(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<Client_id> EndClient_id(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Client_id>(o);
  }
};


}
