// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.TheLastOne
{

using global::System;
using global::FlatBuffers;

public struct Client_Shot_info : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Client_Shot_info GetRootAsClient_Shot_info(ByteBuffer _bb) { return GetRootAsClient_Shot_info(_bb, new Client_Shot_info()); }
  public static Client_Shot_info GetRootAsClient_Shot_info(ByteBuffer _bb, Client_Shot_info obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Client_Shot_info __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Client_Shot_info> CreateClient_Shot_info(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartObject(1);
    Client_Shot_info.AddId(builder, id);
    return Client_Shot_info.EndClient_Shot_info(builder);
  }

  public static void StartClient_Shot_info(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<Client_Shot_info> EndClient_Shot_info(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Client_Shot_info>(o);
  }
};


}
